/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-19T15:57:43.975Z")

@Api(value = "revenue", description = "the revenue API")
public interface RevenueApi {

    @ApiOperation(value = "", nickname = "getRevenueForSalesRep", notes = "Gets total revenue made by a sales rep", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK") })
    @RequestMapping(value = "/revenue/{sales_rep_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Double> getRevenueForSalesRep(@DecimalMin("1") @ApiParam(value = "", required = true) @PathVariable("sales_rep_id") String salesRepId, @ApiParam(value = "") @Valid @RequestParam(value = "date_from", required = false) String dateFrom, @ApiParam(value = "") @Valid @RequestParam(value = "date_to", required = false) String dateTo);


    @ApiOperation(value = "", nickname = "getRevenueFromRegion", notes = "Get total revenue from a region (regions are 'north', 'south', 'east', 'west'", tags={  })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK") })
    @RequestMapping(value = "/revenue/region/{region}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Double> getRevenueFromRegion(@ApiParam(value = "",required=true) @PathVariable("region") String region,@ApiParam(value = "") @Valid @RequestParam(value = "date_from", required = false) String dateFrom,@ApiParam(value = "") @Valid @RequestParam(value = "date_to", required = false) String dateTo);


    @ApiOperation(value = "", nickname = "getTotalRevenue", notes = "Gets total revenue made by the organization", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK") })
    @RequestMapping(value = "/revenue/",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> getTotalRevenue(@ApiParam(value = "") @Valid @RequestParam(value = "date_from", required = false) String dateFrom, @ApiParam(value = "") @Valid @RequestParam(value = "date_to", required = false) String dateTo);

}
