version: '2'
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=sales
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=toor
    ports:
        - "3306:3306"
  api:
    build: ./
    depends_on:
      - database
    restart: always
    ports:
      - "8080:8080"
  ui:
    build: ./src/react-src
    ports:
      - "80:3000"
    restart: always
